POST http://localhost:8080/events
content-type: application/json

{
    "name": "Test Event2",
    "description": "A test event2",
    "location": "A test location2",
    "dateTime": "2025-02-01T15:30:00.000Z"
}