POST http://localhost:8080/events
content-type: application/json

{
    "name": "Test Event3",
    "description": "A test event3",
    "location": "A test location3",
    "dateTime": "2022-02-01T15:30:00.000Z"
}